### ISSUE TITLE
[!] Could not find a default VPC

### ISSUE THREAD

**Issue by mgrennan** [jpignata/fargate#2]
So we don't have a "default" VPC.  (deleted it) 
Need the ability to input the "awsvpc networking" as a command line option.

**Comment by jpignata** [comment]
One design choice I made here in the spirit of "reasonable defaults" was to use the default VPC rather than spinning up an entirely separate VPC or asking the user to select one to not litter a user's account and to prevent option sprawl respectively. My thought was that a user encountering this error could just re-create their default VPC (via http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/default-vpc.html#create-default-vpc).

It'd be nice to help the user out here though. It seems like this could be tackled a number of different ways. If the default VPC isn't available, we could do one or more of the following options:

1. return an error and ask the user to provide a VPC ID when creating new services and load balancers and running new tasks
1. create a new VPC and n subnets (where n = the number of availability zones the account can access)
1. create a new default VPC (which is a single API call)
1. continue to blow up, but return a more useful error message explaining how to create a default VPC

I'm learning toward returning a more useful error message as a user might have had good reason not to want a default VPC.

Any thoughts/opinions? Thanks so much for opening this.

**Comment by lecole** [comment]
I would thing it would be best to provide a VPC ID and Cluster Name on the command line. As we have several Clusters and VPCs that we use to separate out services.

**Comment by jpignata** [comment]
@lecole Thanks. I think I'm sold on adding cluster as a command line option for `task` and `service` commands. 

I'm still not sure on the above VPC question though. Asking the user to provide a VPC ID seems to introduce mental overhead and could potentially create issues. i.e., I create a load balancer in one VPC, and try to use it in another. Now there's another new magic string I need to correlate. I suppose we could default to the default VPC, and just allow it to be overridden (a la option 1 above).

**Comment by lecole** [comment]
@jpignata Sounds like a good plan. But what if you also added the VPC as an option and then also implemented option 1. This would give some control over which VPC you want it to go into (without the error), and also as a default have the "default VPC" as the target deployment location.

**Comment by jpignata** [comment]
@lecole Thanks for the input! I'll tinker with this over the next day or two and try to get a 0.2.0 release together with something to address these two pain points.

**Comment by lecole** [comment]
Sounds good. Great work so far.

**Comment by jpignata** [comment]
Released [v0.2.0](https://github.com/jpignata/fargate/releases/tag/v0.2.0) to address the above.
